apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "dummys.example.immalik.com"
spec:
  group: "example.immalik.com"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "dummys"
    singular: "dummy"
    kind: "dummy"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicas"]
          properties:
            replicas:
              type: "integer"
              minimum: 1
